### ISSUE TITLE
I can see `[object Object]` on form submittions list instead selected answer.

### ISSUE THREAD

**Issue by bieli** [ohmyform/ohmyform#135]
#### What's this issue about?
I can see `[object Object]` on form submittions list instead selected answer.

#### Expected behavior
Real answer value

#### Actual behavior
`[object Object]` in answer values

#### Steps to reproduce
Install from documetion https://ohmyform.com/docs/install/ using docker-compose and prepared image. Add one example form with select start from 1 to 5 and after submit example answer I can see sth. from attachement screen.

#### Environment
localhost + docker-compose from documentation
![Zrzut ekranu z 2021-05-15 11-37-44](https://user-images.githubusercontent.com/183053/118355751-05045000-b572-11eb-8ee8-faa075ccb2cc.png)

**Comment by wodka** [comment]
is this on the mongodb version? this should have been fixed in the latest build (not yet released as a named version)

**Comment by watermelonjuice** [comment]
this bug is still present. will there be a newly named version soon?

**Comment by timdonovanuk** [comment]
Using the simple docker compose example, issue still persists.

**Comment by bckmnn** [comment]
Same here with the simple docker compose example. I tried different things, like switching from sqlite to mongo to postgres, switching from prebuilt to building the image myself from latest master, however I could not solve it this way. 

I finally got it working by using the not so simple docker-compose yml from the root directory, where I removed mailhog since I do not need it.

**Comment by gabek** [comment]
@bckmnn What specific thing changed to fix it?  I'm trying to resolve this myself.

**Comment by bckmnn** [comment]
Hi @gabek, i used this docker-compose file: https://github.com/ohmyform/ohmyform/blob/master/docker-compose.yml
However in the end, i had to much issues with ohmyform and resorted to writing my own little survey tool.

**Comment by wodka** [comment]
fixes are now in master and will be part of 1.0 release
